export const SIGN_IN_EMPLOYEE = "SIGN_IN_EMPLOYEE"
export const SIGN_UP_EMPLOYEE = "SIGN_UP_EMPLOYEE"
export const LOADEMP = "LOADEMP"
export const FAILEMP = "FAILEMP"
export const LOG_OUT = "LOG_OUT"
export const GET_EMP = "GET_EMP"
export const GET_ONE_EMP = "GET_ONE_EMP"