export const SIGN_IN_USER = "SIGN_IN_USER"
export const SIGN_UP_USER = "SIGN_UN_USER"
export const LOAD = "LOAD"
export const FAIL = "FAIL"
export const LOG_OUT = "LOG_OUT"
export const GET_USER = "GET_USER"